apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodeapp-deployment
  labels:
    app: my-nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nodeapp
  template:
    metadata:
      labels:
        app: my-nodeapp
    spec:
      containers:
        - name: my-app-container
          image: image-registry.openshift-image-registry.svc:5000/sanjaysaz-dev/my-nodeapp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeapp-service
spec:
  selector:
    app: my-nodeapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # You can change this to LoadBalancer if needed

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-nodeapp-route
spec:
  to:
    kind: Service
    name: my-nodeapp-service
  port:
    targetPort: 8080
  # You can use 'passthrough', 'reencrypt', or 'edge' based on your requirements
